
module SHAKE256LWRCore #(
    parameter N_LWR = 445, 
    parameter N = 2048,
    parameter P = 16, 
    parameter MAX_COUNT = 1024
    ) (
  // BEETHOVEN-PORTS-BEGIN -- regenerated by Beethoven; edits inside this region will be lost
  input clock,
  input areset,

  input          cmd_shake256_lwr_valid,
  output         cmd_shake256_lwr_ready,
  input  [63:0]  cmd_shake256_lwr_out_addr,
  input  [31:0]  cmd_shake256_lwr_count,
  input  [63:0]  cmd_shake256_lwr_sk_addr,
  input  [63:0]  cmd_shake256_lwr_nonce_addr,
  output         resp_shake256_lwr_valid,
  input          resp_shake256_lwr_ready,
  output         nonce_req_valid,
  input          nonce_req_ready,
  output [31:0]  nonce_req_len,
  output [48:0]  nonce_req_addr_address,
  output         sk_req_valid,
  input          sk_req_ready,
  output [31:0]  sk_req_len,
  output [48:0]  sk_req_addr_address,
  input          nonce_inProgress,
  input          sk_inProgress,
  input          nonce_data_valid,
  output         nonce_data_ready,
  input  [63:0]  nonce_data,
  input          sk_data_valid,
  output         sk_data_ready,
  input  [511:0] sk_data,
  output         out_req_valid,
  input          out_req_ready,
  output [31:0]  out_req_len,
  output [48:0]  out_req_addr_address,
  input          out_isFlushed,
  output         out_data_valid,
  input          out_data_ready,
  output [7:0]   out_data
  // BEETHOVEN-PORTS-END
);

    localparam IDLE = 2'd0;
    localparam COMPUTE = 2'd1;
    localparam RESPONSE = 2'd2;

    localparam NONCE_BYTES = 64 / 8;
    localparam SK_BYTES = 512 / 8;

    reg [1:0] state;

    wire cmd_fire = cmd_shake256_lwr_valid && cmd_shake256_lwr_ready;

    // Accept a command only when all request channels are ready
    assign cmd_shake256_lwr_ready = (state == IDLE)
        && nonce_req_ready
        && sk_req_ready
        && out_req_ready;

    // Issue all memory requests simultaneously on cmd_fire
    assign nonce_req_valid = cmd_fire;
    assign nonce_req_len = NONCE_BYTES;
    assign nonce_req_addr_address = cmd_shake256_lwr_nonce_addr;

    assign sk_req_valid = cmd_fire;
    assign sk_req_len = SK_BYTES;
    assign sk_req_addr_address = cmd_shake256_lwr_sk_addr;

    assign out_req_valid = cmd_fire;
    assign out_req_len = {2'b0, cmd_shake256_lwr_count[31:1]}; // count/2 bytes (2 PRF outputs per byte)
    assign out_req_addr_address = cmd_shake256_lwr_out_addr;

    wire enc_idle;
    wire enc_nonce_ready;
    wire enc_sk_ready;

    assign nonce_data_ready = enc_nonce_ready;
    assign sk_data_ready = enc_sk_ready;

    ShakeLWREncrypt #(
        .N_LWR(N_LWR),
        .N(N),
        .P(P),
        .MAX_COUNT(MAX_COUNT)
    ) encryption_module (
        .clk(clock),
        .rst_n(~areset),
        .start(cmd_fire),
        .nonce(nonce_data),
        .nonce_valid(nonce_data_valid),
        .nonce_ready(enc_nonce_ready),
        .sk(sk_data[N_LWR-1:0]),
        .sk_valid(sk_data_valid),
        .sk_ready(enc_sk_ready),
        .count(cmd_shake256_lwr_count),
        .out_data(out_data),
        .out_valid(out_data_valid),
        .out_ready(out_data_ready),
        .idle(enc_idle)
    );

    assign resp_shake256_lwr_valid = (state == RESPONSE);

    always @(posedge clock) begin
        if (areset) begin
            state <= IDLE;
        end else begin
            case (state)
                IDLE:
                    if (cmd_fire) begin
                        state <= COMPUTE;
                    end
                COMPUTE:
                    if (enc_idle && out_req_ready && out_isFlushed) begin
                        state <= RESPONSE;
                    end
                RESPONSE:
                    if (resp_shake256_lwr_ready) begin
                        state <= IDLE;
                    end
                default:
                    state <= IDLE;
            endcase
        end
    end

endmodule
