// SystolicArrayCore is the Beethoven "AcceleratorCore" for this example: the module that
// implements the accelerator's logic and that Beethoven wires up to the rest of the SoC
// (host command/response queues, DRAM-backed DMA streams, and on-chip scratchpads).
//
// This file is the hand-written Verilog twin of SystolicArrayCore.scala (Beethoven cores can
// be written in Chisel or plain Verilog/SystemVerilog) - it implements the exact same two
// command FSMs and is a good place to see Beethoven's port conventions spelled out explicitly
// instead of hidden behind Chisel bundles.
//
// The port list below is generated by Beethoven from the accelerator's command/response and
// memory-interface declarations (see SystolicArrayCore.scala and SystolicArrayConfig.scala) -
// don't hand-edit inside the BEETHOVEN-PORTS region, it will be overwritten the next time the
// build regenerates this file. Each group of ports follows a fixed naming convention:
//
//   cmd_<name>_*   / resp_<name>_*        - one pair per `BeethovenIO` command this core
//                                           exposes to the host (here: "matmul" and
//                                           "init_weights"). cmd_*_valid/ready is a standard
//                                           ready/valid handshake carrying the command's
//                                           argument fields (addresses, dimensions); the core
//                                           must raise resp_*_valid for exactly one cycle
//                                           (until the host accepts it with resp_*_ready) to
//                                           signal completion back to the host.
//   <name>_req_*, <name>_data_*           - a DMA "reader" (activations) or "writer" (vec_out)
//                                           stream to/from main memory. The core issues a
//                                           request (address + length in bytes) on req_*, then
//                                           streams 128-bit beats through data_* until the
//                                           transfer completes; vec_out additionally exposes
//                                           isFlushed so the core can wait until every queued
//                                           write has actually landed in memory.
//   WeightScratchpad_req_*                - direct read/write access to a small on-chip
//                                           scratchpad (here used to stage weights before
//                                           feeding the systolic array), addressed by a local
//                                           scratchpad address (WeightScratchpad_req_addr)
//                                           rather than a DRAM address.
//   WeightScratchpad_init_* / _wb_*       - bulk DMA paths that fill ("init") or flush
//                                           ("writeback") the scratchpad from/to main memory in
//                                           one streaming transfer, instead of one word at a
//                                           time through _req_*.
//
// "Address()" fields in the Scala command definitions widen to a 49-bit `*_address` signal
// here, and dimension/length fields show up as fixed-width `*_inner_dimension` / `*_len`
// busses.
module SystolicArrayCore #(parameter SYSTOLIC_ARRAY_DIM, DATA_WIDTH_BITS, INT_BITS, FRAC_BITS)(
  // BEETHOVEN-PORTS-BEGIN -- regenerated by Beethoven; edits inside this region will be lost
  input clock,
  input areset,

  input          cmd_matmul_valid,
  output         cmd_matmul_ready,
  input  [19:0]  cmd_matmul_inner_dimension,
  input  [48:0]  cmd_matmul_out_addr_address,
  input  [48:0]  cmd_matmul_act_addr_address,
  input          cmd_init_weights_valid,
  output         cmd_init_weights_ready,
  input  [19:0]  cmd_init_weights_inner_dimension,
  input  [48:0]  cmd_init_weights_wgt_addr_address,
  output         resp_matmul_valid,
  input          resp_matmul_ready,
  output         resp_init_weights_valid,
  input          resp_init_weights_ready,
  output         activations_req_valid,
  input          activations_req_ready,
  output [31:0]  activations_req_len,
  output [48:0]  activations_req_addr_address,
  input          activations_inProgress,
  input          activations_data_valid,
  output         activations_data_ready,
  input  [127:0] activations_data,
  output         vec_out_req_valid,
  input          vec_out_req_ready,
  output [31:0]  vec_out_req_len,
  output [48:0]  vec_out_req_addr_address,
  input          vec_out_isFlushed,
  output         vec_out_data_valid,
  input          vec_out_data_ready,
  output [127:0] vec_out_data,
  output         WeightScratchpad_req_valid,
  input          WeightScratchpad_req_ready,
  output         WeightScratchpad_req_write_enable,
  output [127:0] WeightScratchpad_req_data,
  output [8:0]   WeightScratchpad_req_addr,
  input          WeightScratchpad_resp_valid,
  input  [127:0] WeightScratchpad_resp,
  output         WeightScratchpad_init_valid,
  input          WeightScratchpad_init_ready,
  output [48:0]  WeightScratchpad_init_len,
  output [8:0]   WeightScratchpad_init_scAddr,
  output [48:0]  WeightScratchpad_init_memAddr_address,
  output         WeightScratchpad_wb_valid,
  input          WeightScratchpad_wb_ready,
  output [48:0]  WeightScratchpad_wb_len,
  output [8:0]   WeightScratchpad_wb_scAddr,
  output [48:0]  WeightScratchpad_wb_memAddr_address
  // BEETHOVEN-PORTS-END
);

localparam WEIGHT_INIT_SETTLE_CYCLES = 8; // cycles to let the last scratchpad write land before responding
localparam WEIGHT_QUEUE_DEPTH = 8;        // depth of the FIFO buffering scratchpad reads ahead of the array

// A command's ready/valid handshake "fires" the cycle both sides assert their signal -
// that's the cycle its argument fields are actually consumed.
wire cmd_fire = ???;
wire winit_fire = cmd_init_weights_valid && cmd_init_weights_ready;

// Kick off both DMA streams the same cycle a "matmul" command fires: the writer (vec_out)
// reserves space for the SYSTOLIC_ARRAY_DIM x SYSTOLIC_ARRAY_DIM result up front, and the
// reader (activations) starts streaming the activation matrix in immediately.
assign vec_out_req_valid = cmd_fire;
assign vec_out_req_len = (??? * (DATA_WIDTH_BITS / 8));
assign vec_out_req_addr_address = ???;

assign activations_req_valid = cmd_fire;
assign activations_req_len = ??? * (DATA_WIDTH_BITS / 8);
assign activations_req_addr_address = ???;

// This core never writes the scratchpad's contents back to memory, so the writeback DMA port
// is permanently tied off.
assign WeightScratchpad_wb_valid = 1'b0;
assign WeightScratchpad_wb_len = 'd0;
assign WeightScratchpad_wb_scAddr = 'd0;
assign WeightScratchpad_wb_memAddr_address = 'd0;

// ---------------- matmul FSM ----------------
// IDLE     -> wait for a "matmul" command.
// GO       -> activations/weights are streaming into the SystolicArray submodule below.
// FLUSH    -> array is done computing; wait for the result DMA writer to actually flush
//             (vec_out_isFlushed) so the host can't observe a "done" response before the
//             output has truly landed in memory.
// RESPONSE -> hold resp_matmul_valid until the host accepts it, then return to IDLE.
`define IDLE 0
`define GO 1
`define FLUSH 2
`define RESPONSE 3
reg [1:0] state;

// ---------------- init_weights FSM (drives the scratchpad's init/DMA port) ----------------
// IDLE   -> wait for an "init_weights" command; latch its address/length.
// ISSUE  -> hand the bulk DMA-load request to the scratchpad's init port.
// WAIT   -> wait for the scratchpad to accept/complete the load.
// SETTLE -> burn WEIGHT_INIT_SETTLE_CYCLES so the scratchpad's last write is visible to
//           ordinary reads before anything tries to read the freshly loaded weights back out.
// RESP   -> hold resp_init_weights_valid until the host accepts it, then return to IDLE.
// Note this FSM and the matmul FSM above are mutually exclusive by construction: each one's
// *_ready only asserts while both FSMs sit in their respective IDLE state (see
// cmd_matmul_ready / cmd_init_weights_ready below), so weights are never reloaded mid-matmul.
`define WINIT_IDLE 0
`define WINIT_ISSUE 1
`define WINIT_WAIT 2
`define WINIT_SETTLE 3
`define WINIT_RESP 4
reg [2:0] winit_state;
reg [48:0] storedWgtAddr;
reg [19:0] storedInnerDim;
reg [3:0]  settleCounter;

assign WeightScratchpad_init_valid = winit_state == `WINIT_ISSUE;
assign WeightScratchpad_init_memAddr_address = storedWgtAddr;
assign WeightScratchpad_init_scAddr = 'd0; // weights always load starting at scratchpad address 0
assign WeightScratchpad_init_len = storedInnerDim * (SYSTOLIC_ARRAY_DIM * (DATA_WIDTH_BITS / 8));

// Only accept a new "matmul" command when idle on both FSMs and both DMA streams can take a
// new request (back-pressure from the memory-side queues feeds straight back to the host).
assign cmd_matmul_ready = ???;
assign resp_matmul_valid = ???;

assign cmd_init_weights_ready = winit_state == `WINIT_IDLE && state == `IDLE;
assign resp_init_weights_valid = winit_state == `WINIT_RESP;


always @(posedge clock) begin
  if (areset) begin
    winit_state <= `WINIT_IDLE;
  end else begin
    if (winit_state == `WINIT_IDLE) begin
      if (winit_fire) begin
        storedWgtAddr <= cmd_init_weights_wgt_addr_address;
        storedInnerDim <= cmd_init_weights_inner_dimension;
        winit_state <= `WINIT_ISSUE;
      end
    end else if (winit_state == `WINIT_ISSUE) begin
      if (WeightScratchpad_init_valid && WeightScratchpad_init_ready) begin
        winit_state <= `WINIT_WAIT;
      end
    end else if (winit_state == `WINIT_WAIT) begin
      if (WeightScratchpad_init_ready) begin
        settleCounter <= 'd0;
        winit_state <= `WINIT_SETTLE;
      end
    end else if (winit_state == `WINIT_SETTLE) begin
      settleCounter <= settleCounter + 1'b1;
      if (settleCounter == (WEIGHT_INIT_SETTLE_CYCLES - 1)) begin
        winit_state <= `WINIT_RESP;
      end
    end else if (winit_state == `WINIT_RESP) begin
      if (resp_init_weights_ready) begin
        winit_state <= `WINIT_IDLE;
      end
    end
  end
end

// ---------------- scratchpad-read adapter (feeds the array during matmul) ----------------
// The scratchpad's req/resp port is a plain memory port (one address in, one response some
// cycles later - no inherent backpressure beyond *_req_ready), so this block walks it like a
// simple streaming prefetcher: keep issuing reads at increasing addresses, up to
// WEIGHT_QUEUE_DEPTH in flight at once, and buffer the responses in `weightQueue` so the
// systolic array (which applies its own backpressure via wgt_ready) can consume them at
// whatever rate it's ready for.
reg [8:0]  rdAddr;         // next scratchpad row to read
reg [3:0]  outstanding;    // reads issued but not yet matched with a response
reg [19:0] matmulInnerDim; // total rows to read this matmul, latched from the command

wire doIssueWeightRead = (rdAddr < matmulInnerDim) && (outstanding < WEIGHT_QUEUE_DEPTH);

assign WeightScratchpad_req_valid = doIssueWeightRead;
assign WeightScratchpad_req_write_enable = 1'b0; // this adapter only ever reads
assign WeightScratchpad_req_data = 'd0;
assign WeightScratchpad_req_addr = rdAddr;

wire wgt_queue_deq_valid, wgt_queue_deq_ready;
wire [127:0] wgt_queue_deq_data;

wire sa_idle;

// The actual compute datapath: a SYSTOLIC_ARRAY_DIM x SYSTOLIC_ARRAY_DIM grid of processing
// elements (see SystolicArray.v) that streams activations and weights in, multiply-accumulates
// them in place, and shifts the finished accumulator values out once the inner dimension is
// exhausted. Everything above this point exists to keep its act_in/wgt_in ports fed and to wrap
// its start/done signals in the host-facing command protocol.
SystolicArray #(.DATA_WIDTH_BITS(DATA_WIDTH_BITS), .FRAC_BITS(FRAC_BITS), .INT_BITS(INT_BITS), .SYSTOLIC_ARRAY_DIM(SYSTOLIC_ARRAY_DIM)) sa(
  .clk(clock),
  .rst(areset),

  .act_in(???),
  .act_valid(???),
  .act_ready(???),

  .wgt_in(wgt_queue_deq_data),
  .wgt_valid(wgt_queue_deq_valid),
  .wgt_ready(wgt_queue_deq_ready),

  .accumulator_out(???),
  .accumulator_out_valid(???),
  .accumulator_out_ready(???),

  .ctrl_start_matmul(???),
  .ctrl_start_ready(sa_idle),
  .ctrl_inner_dimension(???)
);

// Top-level matmul FSM (see state diagram in the `define block above): advances from GO to
// FLUSH once the array reports idle (sa_idle) and the result DMA write has been issued and
// fully flushed to memory, then to RESPONSE to signal completion to the host.
always @(posedge clock) begin
  if (areset) begin
    state <= `IDLE;
  end else begin
    if (state == `IDLE) begin
      if (???) begin
        state <= `GO;
      end
    end else if (state == `GO) begin
      if (sa_idle && ???) begin
        state <= `RESPONSE;
      end
    end else if (state == `RESPONSE) begin
      if (???) begin
        state <= `IDLE;
      end
    end
  end
end


always @(posedge clock) begin
  if (areset) begin
    rdAddr <= 'd0;
    outstanding <= 'd0;
    matmulInnerDim <= 'd0;
  end else begin
    if (cmd_fire) begin
      // a new "matmul" command restarts the read sweep from scratchpad address 0
      matmulInnerDim <= cmd_matmul_inner_dimension;
      rdAddr <= 'd0;
      outstanding <= 'd0;
    end else begin
      if (doIssueWeightRead) begin
        rdAddr <= rdAddr + 1'b1;
      end
      // +1 for each read issued this cycle, -1 for each response drained from the queue
      outstanding <= outstanding + doIssueWeightRead - (wgt_queue_deq_valid && wgt_queue_deq_ready);
    end
  end
end

// FIFO between the scratchpad's read responses and the array's weight input - absorbs the
// scratchpad's response latency and any rate mismatch with the array.
WeightQueue #(.WIDTH(SYSTOLIC_ARRAY_DIM * DATA_WIDTH_BITS), .DEPTH(WEIGHT_QUEUE_DEPTH)) weightQueue (
  .clk(clock),
  .rst(areset),

  .enq_valid(WeightScratchpad_resp_valid),
  .enq_ready(),                 // not checked: the scratchpad never returns more responses
                                 // than were requested, and requests are capped by `outstanding`,
                                 // so the queue can never overflow.
  .enq_data(WeightScratchpad_resp),

  .deq_valid(wgt_queue_deq_valid),
  .deq_ready(wgt_queue_deq_ready),
  .deq_data(wgt_queue_deq_data)
);

endmodule
