
module SystolicArrayCore #(parameter SYSTOLIC_ARRAY_DIM, DATA_WIDTH_BITS, INT_BITS, FRAC_BITS)(
  // BEETHOVEN-PORTS-BEGIN -- regenerated by Beethoven; edits inside this region will be lost
  input clock,
  input areset,

  input          cmd_matmul_valid,
  output         cmd_matmul_ready,
  input  [19:0]  cmd_matmul_inner_dimension,
  input  [48:0]  cmd_matmul_out_addr_address,
  input  [48:0]  cmd_matmul_act_addr_address,
  input          cmd_init_weights_valid,
  output         cmd_init_weights_ready,
  input  [19:0]  cmd_init_weights_inner_dimension,
  input  [48:0]  cmd_init_weights_wgt_addr_address,
  output         resp_matmul_valid,
  input          resp_matmul_ready,
  output         resp_init_weights_valid,
  input          resp_init_weights_ready,
  output         activations_req_valid,
  input          activations_req_ready,
  output [31:0]  activations_req_len,
  output [48:0]  activations_req_addr_address,
  input          activations_inProgress,
  input          activations_data_valid,
  output         activations_data_ready,
  input  [127:0] activations_data,
  output         vec_out_req_valid,
  input          vec_out_req_ready,
  output [31:0]  vec_out_req_len,
  output [48:0]  vec_out_req_addr_address,
  input          vec_out_isFlushed,
  output         vec_out_data_valid,
  input          vec_out_data_ready,
  output [127:0] vec_out_data,
  output         WeightScratchpad_req_valid,
  input          WeightScratchpad_req_ready,
  output         WeightScratchpad_req_write_enable,
  output [127:0] WeightScratchpad_req_data,
  output [8:0]   WeightScratchpad_req_addr,
  input          WeightScratchpad_resp_valid,
  input  [127:0] WeightScratchpad_resp,
  output         WeightScratchpad_init_valid,
  input          WeightScratchpad_init_ready,
  output [48:0]  WeightScratchpad_init_len,
  output [8:0]   WeightScratchpad_init_scAddr,
  output [48:0]  WeightScratchpad_init_memAddr_address,
  output         WeightScratchpad_wb_valid,
  input          WeightScratchpad_wb_ready,
  output [48:0]  WeightScratchpad_wb_len,
  output [8:0]   WeightScratchpad_wb_scAddr,
  output [48:0]  WeightScratchpad_wb_memAddr_address
  // BEETHOVEN-PORTS-END
);

localparam WEIGHT_INIT_SETTLE_CYCLES = 8;
localparam WEIGHT_QUEUE_DEPTH = 8;

wire cmd_fire = cmd_matmul_valid && cmd_matmul_ready;
wire winit_fire = cmd_init_weights_valid && cmd_init_weights_ready;

assign vec_out_req_valid = cmd_fire;
assign vec_out_req_len = (SYSTOLIC_ARRAY_DIM * SYSTOLIC_ARRAY_DIM * (DATA_WIDTH_BITS / 8));
assign vec_out_req_addr_address = cmd_matmul_out_addr_address;

assign activations_req_valid = cmd_fire;
assign activations_req_len = (DATA_WIDTH_BITS / 8) * SYSTOLIC_ARRAY_DIM * cmd_matmul_inner_dimension;
assign activations_req_addr_address = cmd_matmul_act_addr_address;

assign WeightScratchpad_wb_valid = 1'b0;
assign WeightScratchpad_wb_len = 'd0;
assign WeightScratchpad_wb_scAddr = 'd0;
assign WeightScratchpad_wb_memAddr_address = 'd0;

// ---------------- matmul FSM ----------------
`define IDLE 0
`define GO 1
`define FLUSH 2
`define RESPONSE 3
reg [1:0] state;

// ---------------- init_weights FSM (drives the scratchpad's init/DMA port) ----------------
`define WINIT_IDLE 0
`define WINIT_ISSUE 1
`define WINIT_WAIT 2
`define WINIT_SETTLE 3
`define WINIT_RESP 4
reg [2:0] winit_state;
reg [48:0] storedWgtAddr;
reg [19:0] storedInnerDim;
reg [3:0]  settleCounter;

assign cmd_matmul_ready = state == `IDLE
        && winit_state == `WINIT_IDLE
        && activations_req_ready
        && vec_out_req_ready;
assign resp_matmul_valid = state == `RESPONSE;

assign cmd_init_weights_ready = winit_state == `WINIT_IDLE && state == `IDLE;
assign resp_init_weights_valid = winit_state == `WINIT_RESP;

assign WeightScratchpad_init_valid = winit_state == `WINIT_ISSUE;
assign WeightScratchpad_init_memAddr_address = storedWgtAddr;
assign WeightScratchpad_init_scAddr = 'd0;
assign WeightScratchpad_init_len = storedInnerDim * (SYSTOLIC_ARRAY_DIM * (DATA_WIDTH_BITS / 8));

always @(posedge clock) begin
  if (areset) begin
    winit_state <= `WINIT_IDLE;
  end else begin
    if (winit_state == `WINIT_IDLE) begin
      if (winit_fire) begin
        storedWgtAddr <= cmd_init_weights_wgt_addr_address;
        storedInnerDim <= cmd_init_weights_inner_dimension;
        winit_state <= `WINIT_ISSUE;
      end
    end else if (winit_state == `WINIT_ISSUE) begin
      if (WeightScratchpad_init_valid && WeightScratchpad_init_ready) begin
        winit_state <= `WINIT_WAIT;
      end
    end else if (winit_state == `WINIT_WAIT) begin
      if (WeightScratchpad_init_ready) begin
        settleCounter <= 'd0;
        winit_state <= `WINIT_SETTLE;
      end
    end else if (winit_state == `WINIT_SETTLE) begin
      settleCounter <= settleCounter + 1'b1;
      if (settleCounter == (WEIGHT_INIT_SETTLE_CYCLES - 1)) begin
        winit_state <= `WINIT_RESP;
      end
    end else if (winit_state == `WINIT_RESP) begin
      if (resp_init_weights_ready) begin
        winit_state <= `WINIT_IDLE;
      end
    end
  end
end

// ---------------- scratchpad-read adapter (feeds the array during matmul) ----------------
reg [8:0]  rdAddr;
reg [3:0]  outstanding;
reg [19:0] matmulInnerDim;

wire doIssueWeightRead = (rdAddr < matmulInnerDim) && (outstanding < WEIGHT_QUEUE_DEPTH);

assign WeightScratchpad_req_valid = doIssueWeightRead;
assign WeightScratchpad_req_write_enable = 1'b0;
assign WeightScratchpad_req_data = 'd0;
assign WeightScratchpad_req_addr = rdAddr;

wire wgt_queue_deq_valid, wgt_queue_deq_ready;
wire [127:0] wgt_queue_deq_data;

WeightQueue #(.WIDTH(SYSTOLIC_ARRAY_DIM * DATA_WIDTH_BITS), .DEPTH(WEIGHT_QUEUE_DEPTH)) weightQueue (
  .clk(clock),
  .rst(areset),

  .enq_valid(WeightScratchpad_resp_valid),
  .enq_ready(),
  .enq_data(WeightScratchpad_resp),

  .deq_valid(wgt_queue_deq_valid),
  .deq_ready(wgt_queue_deq_ready),
  .deq_data(wgt_queue_deq_data)
);

always @(posedge clock) begin
  if (areset) begin
    rdAddr <= 'd0;
    outstanding <= 'd0;
    matmulInnerDim <= 'd0;
  end else begin
    if (cmd_fire) begin
      matmulInnerDim <= cmd_matmul_inner_dimension;
      rdAddr <= 'd0;
      outstanding <= 'd0;
    end else begin
      if (doIssueWeightRead) begin
        rdAddr <= rdAddr + 1'b1;
      end
      outstanding <= outstanding + doIssueWeightRead - (wgt_queue_deq_valid && wgt_queue_deq_ready);
    end
  end
end

wire sa_idle;

SystolicArray #(.DATA_WIDTH_BITS(DATA_WIDTH_BITS), .FRAC_BITS(FRAC_BITS), .INT_BITS(INT_BITS), .SYSTOLIC_ARRAY_DIM(SYSTOLIC_ARRAY_DIM)) sa(
  .clk(clock),
  .rst(areset),

  .act_in(activations_data),
  .act_valid(activations_data_valid),
  .act_ready(activations_data_ready),

  .wgt_in(wgt_queue_deq_data),
  .wgt_valid(wgt_queue_deq_valid),
  .wgt_ready(wgt_queue_deq_ready),

  .accumulator_out(vec_out_data),
  .accumulator_out_valid(vec_out_data_valid),
  .accumulator_out_ready(vec_out_data_ready),

  .ctrl_start_matmul(cmd_fire),
  .ctrl_start_ready(sa_idle),
  .ctrl_inner_dimension(cmd_matmul_inner_dimension)
);

always @(posedge clock) begin
  if (areset) begin
    state <= `IDLE;
  end else begin
    if (state == `IDLE) begin
      if (cmd_fire) begin
        state <= `GO;
      end
    end else if (state == `GO) begin
      if (sa_idle && vec_out_req_ready && vec_out_isFlushed) begin
        state <= `RESPONSE;
      end
    end else if (state == `RESPONSE) begin
      if (resp_matmul_ready) begin
        state <= `IDLE;
      end
    end
  end
end

endmodule
